name: main-workflow

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: run api tests
        run: cd api && npm i && npm run test

      - name: run client tests
        run: cd client && npm i && npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lint api
        run: cd api && npm run lint

      - name: Lint client
        run: cd client && npm run lint
